package cn.tedu.store.dao;

import cn.tedu.store.domain.T_address;

import java.util.List;

public interface T_addressDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int insert(T_address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int insertSelective(T_address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    T_address selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(T_address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(T_address record);
    List<T_address> selectAll();
}