package cn.tedu.store.dao;

import cn.tedu.store.domain.T_dict_areas;

import java.util.List;

public interface T_dict_areasDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_areas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_areas
     *
     * @mbg.generated
     */
    int insert(T_dict_areas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_areas
     *
     * @mbg.generated
     */
    int insertSelective(T_dict_areas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_areas
     *
     * @mbg.generated
     */
    T_dict_areas selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_areas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(T_dict_areas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_areas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(T_dict_areas record);
    List<T_dict_areas> selectAll();
}