package cn.tedu.store.dao;

import cn.tedu.store.domain.T_user;

public interface T_userDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int insert(T_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int insertSelective(T_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    T_user selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(T_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(T_user record);

    /**
     * 通过用户名查询用户信息
     * @param username
     * @return
     */
    T_user getUserByUsername(String username);

    /**
     * 根据email查询,如果存在,返回非0
     * 否则返回 0
     * @param email
     * @return
     */
    Integer getCountByEmail(String email);

    /**
     * 根据phone查询,如果存在,返回非0
     * 否则返回 0
     * @param phone
     * @return
     */
    Integer getCountByPhone(String phone);

    /**
     * 修改用户信息
     * @param user
     */
    void update(T_user user);
    /**
     * 根据id查询用户信息,并返回
     * @param id
     * @return
     */
    T_user getUserById(Integer id);
}